### ISSUE TITLE
Unable to resolve "uint8arrays" (expo)

### ISSUE THREAD

**Issue by simonas-notcat** [decentralized-identity/veramo#1250]
**Bug severity**
5

**Describe the bug**
Unable to use Veramo with expo (react native)

**Observed behaviour**
`Unable to resolve "uint8arrays" from "node_modules/@veramo/key-manager/build/abstract-key-management-system.js"`

**Details**
![IMG_0AC3C01860B9-1](https://github.com/uport-project/veramo/assets/16773277/f1007a9f-3dbc-4efb-8caa-7dd9a1211a6b)

**Additional context**
https://github.com/achingbrain/uint8arrays/issues/53

**Versions (please complete the following information):**
 - Veramo: 5.5.0

**Comment by sgno28** [comment]
Have you found a workaround for this uint8array error? Currently facing it myself when trying to do key management on expo app

**Comment by mirceanis** [comment]
The problem arises from the metro bundler who doesn't natively deal with modules that lack a `main` entry in `package.json`. It tries to look for an index.*js file instead of following javascript trends, so it doesn't look at exports. `uint8arrays` uses `exports` exclusively and has no `main`, and it also lacks an index.js file or equivalents.
Apparently there is a flag that can be enabled for the bundler to look at `exports`: https://metrobundler.dev/docs/package-exports
